bind e setw synchronize-panes on
bind E setw synchronize-panes off
set -g mouse on
set -g set-clipboard on
if-shell 'command -v clip.exe >/dev/null 2>&1' "set -g copy-command 'clip.exe'"
if-shell 'command -v clip.exe >/dev/null 2>&1' '' 'if-shell "command -v pbcopy >/dev/null 2>&1" "set -g copy-command \"pbcopy\""'
if-shell 'command -v clip.exe >/dev/null 2>&1 || command -v pbcopy >/dev/null 2>&1' '' 'if-shell "command -v wl-copy >/dev/null 2>&1" "set -g copy-command \"wl-copy\""'
if-shell 'command -v clip.exe >/dev/null 2>&1 || command -v pbcopy >/dev/null 2>&1 || command -v wl-copy >/dev/null 2>&1' '' 'if-shell "command -v xclip >/dev/null 2>&1" "set -g copy-command \"xclip -selection clipboard -in\""'
if-shell 'command -v clip.exe >/dev/null 2>&1 || command -v pbcopy >/dev/null 2>&1 || command -v wl-copy >/dev/null 2>&1 || command -v xclip >/dev/null 2>&1' '' 'if-shell "command -v xsel >/dev/null 2>&1" "set -g copy-command \"xsel --clipboard --input\""'
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi Escape send-keys -X cancel
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X stop-selection
bind -T copy-mode MouseDragEnd1Pane send-keys -X stop-selection
bind -n MouseDrag1Pane if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" "send-keys -M" "copy-mode -M"
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "copy-mode -e; send-keys -M"
bind -n WheelDownPane select-pane -t= \; send-keys -M

# Plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Initialize tpack. Keep this line at the very bottom of tmux.conf.
run '~/.tmux/plugins/tpm/tpm'
