#!/usr/bin/env bash
set -euo pipefail

# ./updateProxmoxGuestIp.sh --prefix pve
# without prefix
# 192.168.1.10 ubuntu22

# with prefix
# 192.168.1.10 pve-ubuntu22

# Optional prefix argument
PREFIX=""
if [[ "${1:-}" == "--prefix" && -n "${2:-}" ]]; then
    PREFIX="$2"
fi

HOSTS_FILE="/etc/hosts"
BACKUP="/etc/hosts.bak-$(date +%F-%H%M)"
TMP_FILE="$(mktemp)"

cleanup() {
    rm -f "$TMP_FILE"
}

trap cleanup EXIT

has() {
    command -v "$1" >/dev/null 2>&1
}

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    echo "Run this script as root so it can safely update /etc/hosts." >&2
    exit 1
fi

for cmd in qm pct jq sed awk grep cut head cp mv mktemp; do
    if ! has "$cmd"; then
        echo "Missing required command: $cmd" >&2
        exit 1
    fi
done

is_valid_host() {
    [[ "$1" =~ ^[A-Za-z0-9.-]+$ ]]
}

echo "Backing up current /etc/hosts to $BACKUP"
cp "$HOSTS_FILE" "$BACKUP"

# Remove old autogenerated block
sed '/# PVE-AUTO-START/,/# PVE-AUTO-END/d' "$HOSTS_FILE" > "$TMP_FILE"

printf '# PVE-AUTO-START\n' >> "$TMP_FILE"

# Function to get VM/CT name
get_guest_name() {
    local vmid="$1"
    local type="$2"  # "qm" or "pct"
    
    if [[ "$type" == "qm" ]]; then
        qm config "$vmid" 2>/dev/null | awk -F ': ' '/^name:/{print $2}'
    elif [[ "$type" == "pct" ]]; then
        pct config "$vmid" 2>/dev/null | awk -F ': ' '/^hostname:/{print $2}'
    fi
}

# Process VMs (using qm)
echo "Processing VMs..."
for vmid in $(qm list | awk 'NR>1 {print $1}'); do
    name=$(get_guest_name "$vmid" "qm")
    if [[ -z "$name" ]]; then
        echo "VM $vmid has no configured name, skipping."
        continue
    fi
    
    # Final hostname with optional prefix
    if [[ -n "$PREFIX" ]]; then
        host="${PREFIX}-${name}"
    else
        host="$name"
    fi

    if ! is_valid_host "$host"; then
        echo "VM $vmid has invalid hostname '$host', skipping."
        continue
    fi

    # Fetch IPv4 from guest agent (skip 127.x.x.x)
    ip=$(qm guest cmd "$vmid" network-get-interfaces 2>/dev/null \
        | jq -r '.[]?."ip-addresses"[]?."ip-address"?' \
        | grep -E "^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$" \
        | grep -v "^127\." \
        | head -n 1)

    if [[ -n "$ip" ]]; then
        echo "Adding VM: $ip  $host"
        printf '%s    %s\n' "$ip" "$host" >> "$TMP_FILE"
    else
        echo "VM $vmid ($name) has no IP via guest agent."
    fi
done

# Process LXC containers (using pct)
echo "Processing LXC containers..."
for ctid in $(pct list | awk 'NR>1 {print $1}'); do
    name=$(get_guest_name "$ctid" "pct")
    if [[ -z "$name" ]]; then
        echo "Container $ctid has no configured hostname, skipping."
        continue
    fi
    
    # Final hostname with optional prefix
    if [[ -n "$PREFIX" ]]; then
        host="${PREFIX}-${name}"
    else
        host="$name"
    fi

    if ! is_valid_host "$host"; then
        echo "Container $ctid has invalid hostname '$host', skipping."
        continue
    fi

    # Check if container is running
    status=$(pct status "$ctid" 2>/dev/null | awk '{print $2}')
    
    if [[ "$status" != "running" ]]; then
        echo "Container $ctid ($name) is not running, skipping."
        continue
    fi

    # Try multiple methods to get LXC IP address
    
    # Method 1: Try to get IP via pct exec (if container has bash/ip tools)
    ip=""
    
    # Try using ip command inside container
    if [[ -z "$ip" ]]; then
        ip=$(pct exec "$ctid" -- ip -4 -o addr show 2>/dev/null \
            | grep -v "127.0.0.1" \
            | grep -E "inet\s+[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" \
            | awk '{print $4}' \
            | cut -d'/' -f1 \
            | head -n1)
    fi
    
    # Method 2: Try using hostname -I (works on most Linux distros)
    if [[ -z "$ip" ]]; then
        ip=$(pct exec "$ctid" -- hostname -I 2>/dev/null \
            | awk '{print $1}' \
            | grep -v "^127\.")
    fi
    
    # Method 3: Try to get IP from network interface in Proxmox
    if [[ -z "$ip" ]]; then
        # This method checks the network interface on the Proxmox host
        # It's less reliable but works for some network configurations
        iface=$(pct config "$ctid" | grep -E "^net[0-9]:" | head -1)
        if [[ -n "$iface" ]]; then
            # Try to extract IP from the interface name
            # This is a simple approach and might need adjustment for your setup
            # You might need to check the actual bridge interface on the host
            echo "Container $ctid ($name) has network config: $iface"
            echo "Note: Manual IP detection from network config not implemented."
            echo "      Consider installing iproute2 or net-tools in the container."
        fi
    fi

    if [[ -n "$ip" ]]; then
        echo "Adding LXC: $ip  $host"
        printf '%s    %s\n' "$ip" "$host" >> "$TMP_FILE"
    else
        echo "Container $ctid ($name) - could not determine IP address."
        echo "  Make sure the container has networking tools installed:"
        echo "  For Debian/Ubuntu: apt-get install iproute2"
        echo "  For Alpine: apk add iproute2"
        echo "  For CentOS/RHEL: yum install iproute"
    fi
done

printf '# PVE-AUTO-END\n' >> "$TMP_FILE"
mv "$TMP_FILE" "$HOSTS_FILE"
echo "Done."
