#!/bin/bash

# ./updateProxmoxGuestIp.sh --prefix pve
# without prefix
# 192.168.1.10 ubuntu22

# with prefix
# 192.168.1.10 pve-ubuntu22


# Optional prefix argument
PREFIX=""
if [[ "$1" == "--prefix" && -n "$2" ]]; then
    PREFIX="$2"
fi

HOSTS_FILE="/etc/hosts"
BACKUP="/etc/hosts.bak-$(date +%F-%H%M)"

echo "Backing up current /etc/hosts to $BACKUP"
cp $HOSTS_FILE $BACKUP

# Remove old autogenerated block
sed -i '/# PVE-AUTO-START/,/# PVE-AUTO-END/d' $HOSTS_FILE

echo "# PVE-AUTO-START" >> $HOSTS_FILE

for vmid in $(qm list | awk 'NR>1 {print $1}'); do

    # Get VM name
    name=$(qm config $vmid | awk -F ': ' '/^name:/{print $2}')

    # Final hostname with optional prefix
    if [[ -n "$PREFIX" ]]; then
        host="${PREFIX}-${name}"
    else
        host="$name"
    fi

    # Fetch IPv4 from guest agent (skip 127.x.x.x)
    ip=$(qm guest cmd $vmid network-get-interfaces 2>/dev/null \
        | jq -r '.[]?."ip-addresses"[]?."ip-address"?' \
        | grep -E "^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$" \
        | grep -v "^127\." \
        | head -n 1)

    if [[ -n "$ip" ]]; then
        echo "Adding: $ip  $host"
        echo "$ip    $host" >> $HOSTS_FILE
    else
        echo "VM $vmid ($name) has no IP via guest agent."
    fi
done

echo "# PVE-AUTO-END" >> $HOSTS_FILE
echo "Done."
