[tools]
bat = "latest"
bun = "latest"
deno = "latest"
dart = { version = "latest", url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-{{ os() }}-{{ arch() }}-release.zip", version_list_url = "https://storage.googleapis.com/storage/v1/b/dart-archive/o?prefix=channels/stable/release/&delimiter=/", version_regex = 'channels/stable/release/(\d+\.\d+\.\d+)/' }
direnv = "latest"
go = "latest"
node = "lts"
python = "3.13"
rust = "latest"
uv = "latest"
yt-dlp = "latest"

[settings]

[settings.python]
compile = false
precompiled_flavor = "install_only"
